### ISSUE TITLE
X OR Y axis randomly stops functioning

### ISSUE THREAD

**Issue by MemeKeeper** [Luigisvc/Biqu-B1_Custom_Firmware#4]
Hi.
This is the second time this issue occurred. I mainly used your custom firmware because of the wonderful implementation of the BL Touch and UBL. However relatively one month after switching over to your firmware for my SKR V1.4 main board I started experiencing some tripy issues with my prints. On a random layer height, one of my horizontal axis will just unlock. Its always either the X or Y axis but never both. The print will continue as normal but it will basically just print a straight line over and over again causing a mess. The axis won't get stuck, it simply just unlocks and stands still. If the print is relatively longer than 2 hours then this issue occurs.
So to remedy this I checked your github page again for any known issues of a FAQ regarding this. Maybe I just don't properly know how to use Github but I couldn't find anything. However you did release a newer version of your firmware which I thought would be the solution to my troubles.
It was the solution... but only for another month.
Is there anything I can do on my side to check for a solution?

**Comment by Luigisvc** [comment]
I've never received any claim about this behavior from other colleagues using the firmwares, the newest I uploaded because there was an issue with the onboard sd card, that still persists. My printer has skr 2 and I cannot test firmwares for other boards. 

But your description reminds me a problem I had on 2.9.3 firmware that was not starting the internal fans, then the drivers got hot during print and stopped. Maybe your internal fan are died, or your drivers is getting hot due to voltage issue, I would either open the bottom panel and check during a print, and if the fans are working, I would reduce the drivers voltages, i think standard in 0.800 A and you can reduce to 0.700 and see if works. The only downside is that you will have to print slower to not lose steps.
Please return with your findings.
And thanks for the compliments.

**Comment by MemeKeeper** [comment]
Thanks! I will give it a go. Another user on Reddit also mentioned something about the stepper drivers getting too hot.  But both the little fans inside is spinning, they're practically brand new I replaced them within the month. However I did print a fan silencer for the fan pulling air from the outside. It was was printed when I first got the printer back in 2021. After removing it the airflow is much better and the print I left overnight is still going strong. I apologise for thinking it might have been your firmware but an update did however fixed for a month so I thought the two might have been connected. Thanks for being helpful and friendly in any case! I will report back when this this issue occurs again and let you know

**Comment by Luigisvc** [comment]
> Thanks! I will give it a go. Another user on Reddit also mentioned something about the stepper drivers getting too hot. But both the little fans inside is spinning, they're practically brand new I replaced them within the month. However I did print a fan silencer for the fan pulling air from the outside. It was was printed when I first got the printer back in 2021. After removing it the airflow is much better and the print I left overnight is still going strong. I apologise for thinking it might have been your firmware but an update did however fixed for a month so I thought the two might have been connected. Thanks for being helpful and friendly in any case! I will report back when this this issue occurs again and let you know

thank you for the update! I will close the issue.
